### ISSUE TITLE
Recontruction fails without error

### ISSUE THREAD

**Issue by matthieu-haudiquet** [evolbioinfo/pastml#11] opened 2020-01-16 13:55 UTC
Hi, 

thanks for this great software ! 

I have found an incoherent behavior in pastml (ML methods). It seems to appear when there are too many tips of the tree with the same trait. In this example, there is one trait with two categories (0 or 1). The internal nodes returned are all "0", even though 3976 out of 3980 tips are "1".

` pastml --prediction_method MAP -m F81 -t tree/named_tree.txt -d fam23460.txt -s ',' -o results.txt `

[fam23460.txt](https://github.com/evolbioinfo/pastml/files/4071587/fam23460.txt)
[named_tree.txt](https://github.com/evolbioinfo/pastml/files/4071588/named_tree.txt)

Best, 

Matthieu

**Comment by annazhukova** [comment] 2020-01-16 16:47
Hi Matthieu,

Thank you very much for reporting this issue! 

The problem is not due to the low number of 0s, but rather to the specificity of your tree with branches of very different scales, varying from ~10-7 to ~10-1, with 1s and 0s present in a cluster with very short branches. 

But in any case, you are right, the all internal 0s result is totally a bug! I've found where it originates from (the optimisation method of scipy.optimize) and am now working on a way to fix it (hopefully soon).

Cheers,
Anna

**Comment by annazhukova** [comment] 2020-01-17 10:58
Dear Matthieu,

This issue should be fixed in version [1.9.23](https://github.com/evolbioinfo/pastml/releases/tag/1.9.23) (pip3 install pastml==1.9.23) and on [pastml.pasteur.fr](https://pastml.pasteur.fr/).

Thanks again for reporting it!

Anna

**Comment by matthieu-haudiquet** [comment] 2020-01-17 11:22
Dear Anna, 
Thank you so much. Will test asap

Best, 
Matt

**Closed** 2020-01-17 11:22 UTC
